const state={colors:[],query:'',use:'הכול'};
const $=s=>document.querySelector(s);
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}
function contrast(hex){const raw=hex.replace('#','');const r=parseInt(raw.slice(0,2),16),g=parseInt(raw.slice(2,4),16),b=parseInt(raw.slice(4,6),16);return ((r*299+g*587+b*114)/1000)>=145?'#0f172a':'#fff'}
function esc(x){return String(x||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
async function copy(text,msg){await navigator.clipboard.writeText(text);toast(msg||'הועתק')}
function colorPrompt(c){return `השתמש בצבע מספר ${c.number} מתוך colors. הצבע המדויק הוא ${c.value}, ערך HSL: ${c.hsl||'לא צוין'}. שם שימושי: ${c.name}. השתמש בו באתר החדש לפי הצורך כרקע, כותרת, כפתור, מסגרת, טבלה או הדגשה. שמור על עברית RTL מלאה, התאמה לנייד ולמחשב, ניגודיות טובה, ללא גלילה אופקית, תוכן אמיתי בלבד, והפרדה בין HTML, CSS ו-JavaScript.`}
function match(c){const q=state.query.trim().toLowerCase();const hay=[c.number,c.id,c.name,c.value,c.hsl,...(c.use||[])].join(' ').toLowerCase();return (state.use==='הכול'||(c.use||[]).includes(state.use))&&(!q||hay.includes(q))}
function card(c){const text=contrast(c.value);return `<article class="color-card" id="${esc(c.id)}"><div class="color-swatch-large" style="background:${esc(c.value)};color:${text}"><div><div class="color-number">${c.number}</div><strong>${esc(c.value)}</strong></div></div><div class="color-body"><h2>${esc(c.name)}</h2><div class="color-meta"><div class="color-pill">${esc(c.value)}</div><div class="color-pill">${esc(c.hsl||'')}</div></div><div class="color-use">${esc((c.use||[]).slice(0,7).join(' · '))}</div><div class="color-copy"><button class="main" data-copy-prompt="${esc(c.id)}" type="button">העתק Prompt ל-GPT</button><button data-copy-value="${esc(c.id)}" type="button">העתק HEX</button><button data-copy-css="${esc(c.id)}" type="button">העתק CSS</button></div></div></article>`}
function render(){const list=state.colors.filter(match);$('#colorStats').textContent=`מוצגים ${list.length} צבעים מתוך ${state.colors.length}`;$('#colorGrid').innerHTML=list.map(card).join('')}
async function init(){const data=await fetch('design-tokens.json',{cache:'no-store'}).then(r=>r.json());state.colors=data.tokens.filter(t=>t.type==='color'&&/^#[0-9A-Fa-f]{6}$/.test(t.value||'')).map((t,i)=>({...t,number:String(i+1).padStart(3,'0')}));const uses=[...new Set(state.colors.flatMap(c=>c.use||[]))].sort();$('#colorUseFilter').innerHTML='<option value="הכול">הכול</option>'+uses.map(u=>`<option value="${esc(u)}">${esc(u)}</option>`).join('');$('#colorSearch').addEventListener('input',e=>{state.query=e.target.value;render()});$('#colorUseFilter').addEventListener('change',e=>{state.use=e.target.value;render()});document.body.addEventListener('click',e=>{const p=e.target.closest('[data-copy-prompt]');const v=e.target.closest('[data-copy-value]');const css=e.target.closest('[data-copy-css]');const id=p?.dataset.copyPrompt||v?.dataset.copyValue||css?.dataset.copyCss;if(!id)return;const c=state.colors.find(x=>x.id===id);if(!c)return;if(p)return copy(colorPrompt(c),'הועתק Prompt צבע ל-GPT');if(v)return copy(c.value,'הועתק HEX');if(css)return copy(`:root{--selected-color:${c.value};}`,'הועתק CSS')});$('#copyVisibleColors').addEventListener('click',()=>{const list=state.colors.filter(match).slice(0,30);copy('בחרתי צבעים מתוך colors:\n'+list.map(colorPrompt).join('\n\n'),'הועתק Prompt צבעים מוצגים')});render()}
init().catch(e=>{$('#colorStats').textContent='שגיאה בטעינת הצבעים';console.error(e)});