const state={colors:[],family:'כחולים',shade:'הכול',query:'',use:'הכול'};
const $=s=>document.querySelector(s);
const families=[['כחולים','#2563eb'],['ירוקים','#22c55e'],['אדומים','#ef4444'],['צהובים','#eab308'],['זהב','#d4af37'],['נייטרליים','#64748b'],['כהים','#0f172a'],['הכול','#111827']];
const shades=[['הכול',''],['בהיר','בהיר'],['בינוני','בינוני'],['כהה','כהה']];
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
function esc(x){return String(x||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function contrast(hex){const r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16);return((r*299+g*587+b*114)/1000)>=145?'#0f172a':'#fff'}
function lightness(hsl){const m=String(hsl||'').match(/(\d+)%\)$/);return m?Number(m[1]):50}
function hue(hsl){const m=String(hsl||'').match(/hsl\((\d+)/);return m?Number(m[1]):0}
function familyOf(c){const h=hue(c.hsl);const name=[c.name,...(c.use||[])].join(' ');if(name.includes('זהב'))return'זהב';if(h>=190&&h<=250)return'כחולים';if(h>=80&&h<=170)return'ירוקים';if(h<=20||h>=340)return'אדומים';if(h>=35&&h<=75)return'צהובים';if(lightness(c.hsl)<=18)return'כהים';if(c.use?.some(x=>['רשמי','טבלאות'].includes(x)))return'נייטרליים';return'נייטרליים'}
function shadeOf(c){const l=lightness(c.hsl);if(l>=70)return'בהיר';if(l<=35)return'כהה';return'בינוני'}
async function copy(text,msg){await navigator.clipboard.writeText(text);toast(msg||'הועתק')}
function colorPrompt(c){return `השתמש בצבע מספר ${c.number}: ${c.value}. HSL: ${c.hsl||'לא צוין'}. משפחה: ${c.family}. גוון: ${c.shade}. השתמש בו באתר כרקע, כותרת, כפתור, מסגרת, טבלה או הדגשה לפי ההקשר. חובה: עברית RTL, התאמה לנייד ולמחשב, ניגודיות טובה, ללא גלילה אופקית, תוכן אמיתי בלבד, והפרדה בין HTML, CSS ו-JavaScript.`}
function match(c){const q=state.query.trim().toLowerCase();const hay=[c.number,c.id,c.name,c.value,c.hsl,c.family,c.shade,...(c.use||[])].join(' ').toLowerCase();return(state.family==='הכול'||c.family===state.family)&&(state.shade==='הכול'||c.shade===state.shade)&&(state.use==='הכול'||(c.use||[]).includes(state.use))&&(!q||hay.includes(q))}
function familyButtons(){ $('#familyStrip').innerHTML=families.map(([name,color])=>`<button class="family ${state.family===name?'active':''}" data-family="${name}" type="button"><span style="background:${color}"></span>${name}</button>`).join('') }
function shadeButtons(){ $('#shadeStrip').innerHTML=shades.map(([name])=>`<button class="shade ${state.shade===name?'active':''}" data-shade="${name}" type="button">${name}</button>`).join('') }
function card(c){const text=contrast(c.value);return `<article class="color-card quick" id="${esc(c.id)}"><button class="swatch-button" data-copy-prompt="${esc(c.id)}" style="background:${esc(c.value)};color:${text}" type="button"><span>${c.number}</span></button><div class="color-body compact"><div class="color-line"><b>${esc(c.value)}</b><small>${esc(c.hsl||'')}</small></div><div class="quick-actions"><button class="main" data-copy-prompt="${esc(c.id)}" type="button">העתק Prompt</button><button data-copy-value="${esc(c.id)}" type="button">HEX</button></div></div></article>`}
function render(){familyButtons();shadeButtons();const list=state.colors.filter(match);$('#colorStats').textContent=`${state.family} · ${state.shade} · ${list.length} צבעים`;$('#colorGrid').innerHTML=list.map(card).join('')}
async function init(){const data=await fetch('design-tokens.json',{cache:'no-store'}).then(r=>r.json());state.colors=data.tokens.filter(t=>t.type==='color'&&/^#[0-9A-Fa-f]{6}$/.test(t.value||'')).map((t,i)=>({...t,number:String(i+1).padStart(3,'0')})).map(c=>({...c,family:familyOf(c),shade:shadeOf(c)}));const uses=[...new Set(state.colors.flatMap(c=>c.use||[]))].sort();$('#colorUseFilter').innerHTML='<option value="הכול">כל השימושים</option>'+uses.map(u=>`<option value="${esc(u)}">${esc(u)}</option>`).join('');$('#colorSearch').addEventListener('input',e=>{state.query=e.target.value;render()});$('#colorUseFilter').addEventListener('change',e=>{state.use=e.target.value;render()});document.body.addEventListener('click',e=>{const fam=e.target.closest('[data-family]');if(fam){state.family=fam.dataset.family;render();return}const sh=e.target.closest('[data-shade]');if(sh){state.shade=sh.dataset.shade;render();return}const p=e.target.closest('[data-copy-prompt]');const v=e.target.closest('[data-copy-value]');const id=p?.dataset.copyPrompt||v?.dataset.copyValue;if(!id)return;const c=state.colors.find(x=>x.id===id);if(!c)return;if(p)return copy(colorPrompt(c),'הועתק Prompt צבע');if(v)return copy(c.value,'הועתק HEX')});$('#copyVisibleColors').addEventListener('click',()=>{const list=state.colors.filter(match).slice(0,20);copy('סט צבעים נבחר מתוך colors:\n'+list.map(colorPrompt).join('\n\n'),'הועתק סט צבעים')});render()}
init().catch(e=>{$('#colorStats').textContent='שגיאה בטעינת הצבעים';console.error(e)});