const state={data:null,cat:'הכול',use:'הכול',q:''};
const $=s=>document.querySelector(s);
function toast(m,ok=true){const t=$('#toast');t.textContent=m;t.style.background=ok?'#052E16':'#7F1D1D';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
async function copy(txt,msg){try{await navigator.clipboard.writeText(txt||'');toast(msg)}catch(e){toast('ההעתקה נכשלה',false)}}
function match(t){const q=state.q.trim().toLowerCase();const hay=[t.id,t.name,t.category,t.type,t.value,...(t.use||[])].join(' ').toLowerCase();return (state.cat==='הכול'||t.category===state.cat)&&(state.use==='הכול'||(t.use||[]).includes(state.use))&&(!q||hay.includes(q))}
function preview(t){if(t.type==='color')return '<div class="preview" style="background:'+t.value+';color:'+t.contrast+'"><b>'+t.value+'</b><br>'+t.hsl+'</div>';if(t.type==='font')return '<div class="preview" style="font-family:'+t.value+',Arial,sans-serif"><b>כותרת בעברית</b><br>טקסט לדוגמה בגופן הזה.</div>';if(t.type==='font-size')return '<div class="preview" style="font-size:'+t.value+'">דוגמת טקסט בגודל הזה</div>';return '<div class="preview">'+t.name+'<br><span class="meta">'+(t.use||[]).slice(0,4).join(' · ')+'</span></div>'}
function card(t){return '<article class="card"><span class="badge">'+t.category+'</span><h3>'+t.name+'</h3>'+preview(t)+'<div class="meta">'+(t.use||[]).join(' · ')+'</div><div class="code">'+(t.css||t.value||'')+'</div><div class="actions"><button class="main" data-copy="prompt" data-id="'+t.id+'">העתק Prompt ל-GPT</button><button data-copy="css" data-id="'+t.id+'">העתק CSS</button><button data-copy="value" data-id="'+t.id+'">העתק ערך</button></div></article>'}
function render(){const list=state.data.tokens.filter(match);$('#stats').innerHTML='<div class="stat">tokens: '+state.data.tokens.length+'</div><div class="stat">מוצגים: '+list.length+'</div><div class="stat">קטגוריות: '+state.data.categories.length+'</div>';$('#grid').innerHTML=list.map(card).join('')}
function chips(el,items,key){$(el).innerHTML=['הכול',...items].map(x=>'<button class="chip '+(state[key]===x?'active':'')+'" data-'+key+'="'+x+'">'+x+'</button>').join('')}
async function init(){state.data=await fetch('design-tokens.json',{cache:'no-store'}).then(r=>r.json());chips('#cats',state.data.categories,'cat');chips('#uses',state.data.uses.slice(0,28),'use');render();document.body.addEventListener('click',e=>{const c=e.target.closest('[data-cat]');if(c){state.cat=c.dataset.cat;chips('#cats',state.data.categories,'cat');render()}const u=e.target.closest('[data-use]');if(u){state.use=u.dataset.use;chips('#uses',state.data.uses.slice(0,28),'use');render()}const b=e.target.closest('[data-copy]');if(b){const t=state.data.tokens.find(x=>x.id===b.dataset.id);copy(t.copy[b.dataset.copy]||'',b.dataset.copy==='prompt'?'הועתק Prompt':'הועתק')}});$('#q').addEventListener('input',e=>{state.q=e.target.value;render()})}
init().catch(e=>toast('שגיאה בטעינת Smart Builder',false));
